language: go
before_install:
  - go get github.com/ogier/pflag
  - go get github.com/mitchellh/gox
  - go get github.com/Sirupsen/logrus
  - gox -build-toolchain -osarch="darwin/amd64 linux/amd64 windows/amd64"

script: make
deploy:
  provider: releases
  api_key:
    secure: Z55l9blwOv870mSOatQIKDkKL8UMBfuvTOj+RYyPC80W+IoAspomgS9yK2dHwcWoR2n2M5WwCLRcKYqQu5UHpqeGr4LnmlhyeWoA0fbRqYq+4IRG/xC6qfp99r9NTKjW9GHz7ThRiJBTrYbVve5Rc8wnD9SmAr5zSXufMseo/KU=
  file:
    - bin/windows/conoha-ojs.windows.amd64.zip
    - bin/darwin/conoha-ojs.osx.amd64.gz
    - bin/linux/conoha-ojs.linux.amd64.gz

  skip_cleanup: true
  on:
    tags: true
    repo: hironobu-s/conoha-ojs
    all_branches: true
